### ISSUE TITLE
转换模型后无法读取

### ISSUE THREAD

**Issue by FightAllDays** [ChineseGLUE/ChineseGLUE#92]
Traceback (most recent call last):
  File "E:/Code/ChineseGLUE-master/ChineseGLUE-master/baselines/models_pytorch/classifier_pytorch/run_classifier.py", line 522, in <module>
    main()
  File "E:/Code/ChineseGLUE-master/ChineseGLUE-master/baselines/models_pytorch/classifier_pytorch/run_classifier.py", line 460, in main
    config = config_class.from_pretrained(args.config_name if args.config_name else args.model_name_or_path, num_labels=num_labels, finetuning_task=args.task_name)
  File "E:\Code\ChineseGLUE-master\ChineseGLUE-master\baselines\models_pytorch\classifier_pytorch\transformers\configuration_utils.py", line 154, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File "E:\Code\ChineseGLUE-master\ChineseGLUE-master\baselines\models_pytorch\classifier_pytorch\transformers\configuration_utils.py", line 187, in from_json_file
    return cls.from_dict(json.loads(text))
  File "D:\anaconda\envs\py37\lib\json\__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
使用环境为python3.8 求大佬指导。。。

**Comment by BlackWaterDrop** [comment]
> Traceback (most recent call last): File "E:/Code/ChineseGLUE-master/ChineseGLUE-master/baselines/models_pytorch/classifier_pytorch/run_classifier.py", line 522, in main() File "E:/Code/ChineseGLUE-master/ChineseGLUE-master/baselines/models_pytorch/classifier_pytorch/run_classifier.py", line 460, in main config = config_class.from_pretrained(args.config_name if args.config_name else args.model_name_or_path, num_labels=num_labels, finetuning_task=args.task_name) File "E:\Code\ChineseGLUE-master\ChineseGLUE-master\baselines\models_pytorch\classifier_pytorch\transformers\configuration_utils.py", line 154, in from_pretrained config = cls.from_json_file(resolved_config_file) File "E:\Code\ChineseGLUE-master\ChineseGLUE-master\baselines\models_pytorch\classifier_pytorch\transformers\configuration_utils.py", line 187, in from_json_file return cls.from_dict(json.loads(text)) File "D:\anaconda\envs\py37\lib\json__init__.py", line 343, in loads s = s.decode(detect_encoding(s), 'surrogatepass') UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte 使用环境为python3.8 求大佬指导。。。

请问解决了吗？
